package com.mathbot.pay.lightning

import com.mathbot.pay.bitcoin.MilliSatoshi
import com.mathbot.pay.json.{FiniteDurationToSecondsReader, FiniteDurationToSecondsWriter}
import play.api.libs.json.Json

import scala.concurrent.duration.{DurationInt, FiniteDuration}

/**
 * Create an invoice for {msatoshi} with {label} and {description} with optional {expiry} seconds (default 1 week), optional {fallbacks} address list(default empty list) and optional {preimage} (default autogenerated)
 * invoice msatoshi label description [expiry] [fallbacks] [preimage] [exposeprivatechannels] [cltv]
 * https://github.com/ElementsProject/lightning/blob/master/doc/lightning-invoice.7.md
 *
 * @param msatoshi
 * @param label
 * @param description
 * @param expiry
 *
 *  *On failure, an error is returned and no invoice is created.
 * If the lightning process fails before responding, the caller should
 * use lightning-listinvoices(7) to query whether this invoice was created or not.
 *
 * The following error codes may occur:
 *
 * -1: Catchall nonspecific error.
 * 900: An invoice with the given label already exists.
 * 901: An invoice with the given preimage already exists.
 * 902: None of the specified exposeprivatechannels were usable.
 */
case class LightningInvoice(
    msatoshi: MilliSatoshi,
    label: String,
    description: String,
    expiry: Option[FiniteDuration] = Some(7.days),
    preimage: Option[String]
)
//                          fallbacks: Option[String] = None,
//                          preimage: Option[String] = None,
//                          exposeprivatechannels: Option[String] = None)
    extends LightningJson

object LightningInvoice extends FiniteDurationToSecondsWriter with FiniteDurationToSecondsReader {
  implicit val formatLightningInvoice = Json.format[LightningInvoice]
}
