package com.mathbot.pay.lightning

import com.mathbot.pay.bitcoin.MilliSatoshi

import scala.concurrent.duration.{Duration, FiniteDuration}

/**
 * Create an invoice for {msatoshi} with {label} and {description} with optional {expiry} seconds (default 1 week), optional {fallbacks} address list(default empty list) and optional {preimage} (default autogenerated)
 * invoice msatoshi label description [expiry] [fallbacks] [preimage] [exposeprivatechannels] [cltv]
 * https://github.com/ElementsProject/lightning/blob/master/doc/lightning-invoice.7.md
 *
 * @param msatoshi
 * @param label
 * @param description
 * @param expiry
 */
case class LightningInvoice(
    msatoshi: MilliSatoshi,
    label: String,
    description: String,
    expiry: Option[FiniteDuration] = Some(Duration("7 days").asInstanceOf[FiniteDuration]),
    preimage: Option[String]
)
//                          fallbacks: Option[String] = None,
//                          preimage: Option[String] = None,
//                          exposeprivatechannels: Option[String] = None)
    extends LightningJson
