name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # todo: java 11...
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Cache sbt
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.sbt
#            ~/.ivy2/cache
#            ~/.coursier/cache/v1
#            ~/.cache/coursier/v1
#            ~/AppData/Local/Coursier/Cache/v1
#            ~/Library/Caches/Coursier/v1
#          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
    - name: compile
      run: sbt compile
    - name: test compile
      run: "sbt test:compile"
    - name: Run tests
      run: sbt test
    - name: formatting
      run: sbt scalafmtCheckAll
    - name: Codecov
      uses: codecov/codecov-action@v1
